# Generated by Django 4.2 on 2026-05-13 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registrations', models.PositiveIntegerField(default=0, verbose_name='إجمالي التسجيلات')),
                ('approved', models.PositiveIntegerField(default=0, verbose_name='الموافق عليها')),
                ('pending', models.PositiveIntegerField(default=0, verbose_name='قيد الانتظار')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='المرفوضة')),
                ('drivers', models.PositiveIntegerField(default=0, verbose_name='المتسابقون')),
                ('navigators', models.PositiveIntegerField(default=0, verbose_name='الملاحون')),
                ('male', models.PositiveIntegerField(default=0, verbose_name='الذكور')),
                ('female', models.PositiveIntegerField(default=0, verbose_name='الإناث')),
                ('region_breakdown', models.JSONField(blank=True, default=dict, verbose_name='توزيع المناطق')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إحصائية',
                'verbose_name_plural': 'الإحصائيات',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16)], verbose_name='العمر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('nationality', models.CharField(max_length=50, verbose_name='الجنسية')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('category', models.CharField(choices=[('D', 'متسابق'), ('N', 'ملاح')], max_length=1, verbose_name='الفئة')),
                ('has_driving_license', models.BooleanField(verbose_name='رخصة القيادة')),
                ('has_sports_license', models.BooleanField(verbose_name='الرخصة الرياضية')),
                ('sports_license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الرخصة الرياضية')),
                ('has_previous_experience', models.BooleanField(verbose_name='خبرة سابقة')),
                ('race_types', models.JSONField(blank=True, default=list, verbose_name='أنواع السباقات')),
                ('number_of_races', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد السباقات')),
                ('years_of_experience', models.CharField(blank=True, choices=[('1-2', 'من 1 إلى 2 سنة'), ('2-5', 'من 2 إلى 5 سنوات'), ('5+', 'أكثر من 5 سنوات')], max_length=3, verbose_name='سنوات الخبرة')),
                ('desert_driving_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم القيادة الصحراوية')),
                ('program_goal', models.TextField(verbose_name='الهدف من البرنامج')),
                ('committed_to_5_days', models.BooleanField(verbose_name='الالتزام بـ 5 أيام')),
                ('health_conditions', models.TextField(blank=True, verbose_name='الحالات الصحية')),
                ('residence_region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('medina', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('baha', 'الباحة'), ('northern', 'المنطقة الشمالية'), ('qassim', 'القصيم'), ('hail', 'حائل'), ('jizan', 'جازان'), ('najran', 'نجران')], max_length=20, verbose_name='منطقة الإقامة')),
                ('can_travel', models.BooleanField(verbose_name='القدرة على السفر')),
                ('profile_photo', models.ImageField(upload_to='photos/', verbose_name='الصورة الشخصية')),
                ('experience_docs', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='مستندات الخبرة')),
                ('status', models.CharField(choices=[('P', 'قيد الانتظار'), ('A', 'موافق عليه'), ('R', 'مرفوض'), ('W', 'متراجع عنه')], default='P', max_length=1, verbose_name='حالة التسجيل')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المسؤول')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة من قبل')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مسؤول'), ('reviewer', 'مراجع'), ('viewer', 'عارض')], default='viewer', max_length=20, verbose_name='الدور')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='القسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مسؤول',
                'verbose_name_plural': 'المسؤولون',
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['email'], name='registratio_email_5e74cb_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['id_number'], name='registratio_id_numb_d1f514_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['phone'], name='registratio_phone_630afb_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_76ed6e_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['application_date'], name='registratio_applica_6ba3cd_idx'),
        ),
    ]
