# Generated by Django 4.2 on 2026-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=True, verbose_name='التسجيل متاح')),
                ('closed_message', models.TextField(default='عذراً، فترة التسجيل منتهية حالياً. يرجى متابعة قنواتنا الرسمية لأي تحديثات.', verbose_name='رسالة إغلاق التسجيل')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='موافق على الشروط والأحكام'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='program_goal',
            field=models.TextField(verbose_name='ما هو هدفك من التسجيل في البرنامج'),
        ),
    ]
