# Generated by Django 4.2 on 2026-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_sitesettings_registration_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='has_driving_license',
            field=models.BooleanField(verbose_name='هل لديك رخصة قيادة سارية؟'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='has_previous_experience',
            field=models.BooleanField(verbose_name='هل لديك خبرة سابقة في مجال رياضة السيارات؟'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='has_sports_license',
            field=models.BooleanField(verbose_name='هل لديك رخصة سباق مصدرة من الاتحاد السعودي للسيارات؟'),
        ),
    ]
